Netevia/Models/DepartmentViewModel.cs
namespace Netevia.Models;

public class DepartmentViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Floor { get; set; }
}

Netevia/Models/EmployeeViewModel.cs
using Netevia.Domain;
using Netevia.Domain.Enums;

namespace Netevia.Models;

public class EmployeeViewModel
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public Gender Gender { get; set; }
    public DepartmentViewModel? Department { get; set; }
}

public class AddEmployeeModel
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public Gender Gender { get; set; }
    public int? DepartmentId { get; set; }
    public List<int> ExperienceIds { get; set; }
}

public class EditEmployeeViewModel : AddEmployeeModel
{
    public int Id { get; set; }
}

Netevia/Models/ErrorViewModel.cs
namespace Netevia.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Netevia/Models/ProgrammingLanguageViewModel.cs
namespace Netevia.Models;

public class ProgrammingLanguageViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
}

Netevia/Models/UserViewModel.cs
namespace Netevia.Models;

public class UserViewModel
{
    public string Username { get; set; }
    public string Password { get; set; }
}

Netevia/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Netevia.Features.Interfaces;
using Netevia.Models;

namespace Netevia.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    public async Task<IActionResult> Add(UserViewModel model)
    {
        if (!ModelState.IsValid) return View(model);

        await _authService.CreateUser(model);
        
        TempData["Notification"] = "Registration successful! Welcome, " + model.Username + ".";
            
        return RedirectToPage("/Authenticate");
    }
}

Netevia/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Netevia.Authorization;
using Netevia.Features.Interfaces;
using Netevia.Models;

namespace Netevia.Controllers;

[Authorize]
public class EmployeeController : Controller
{
    private readonly IEmployeeService _employeeService;
    private readonly IDepartmentService _departmentService;
    private readonly IProgrammingLanguageService _programmingLanguageService;

    public EmployeeController(
        IEmployeeService employeeService, 
        IDepartmentService departmentService, 
        IProgrammingLanguageService programmingLanguageService)
    {
        _employeeService = employeeService;
        _departmentService = departmentService;
        _programmingLanguageService = programmingLanguageService;
    }

    public async Task<IActionResult> Index(string searchString)
    {
        var employees = await _employeeService.GetAll(searchString);
        return View(employees.ToList());
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        var departments = await _departmentService.GetAll();
        var programmingLanguages = await _programmingLanguageService.GetAll();
        
        ViewBag.Departments = new SelectList(departments, "Id", "Name");
        ViewBag.ProgrammingLanguages = new SelectList(programmingLanguages, "Id", "Name");
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(AddEmployeeModel employee)
    {
        if (!ModelState.IsValid) return View(employee);
        await _employeeService.Add(employee);
        return RedirectToAction(nameof(Index));
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var employee = await _employeeService.GetById(id);
        var departments = await _departmentService.GetAll();
        var programmingLanguages = await _programmingLanguageService.GetAll();
        
        ViewBag.Departments = new SelectList(departments, "Id", "Name", employee.DepartmentId);
        ViewBag.ProgrammingLanguages = new SelectList(programmingLanguages, "Id", "Name", employee.ExperienceIds);
        
        return View(employee);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditEmployeeViewModel employee)
    {
        if (!ModelState.IsValid) return View(employee);
        await _employeeService.Edit(id, employee);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _employeeService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Netevia/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Netevia.Models;

namespace Netevia.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Netevia/Views/Employee/Add.cshtml
@model Netevia.Models.AddEmployeeModel

@{
    ViewBag.Title = "Add Employee";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Add</legend>

        <p>
            First Name <br/>
            @Html.EditorFor(model => model.FirstName)
        </p>

        <p>
            Last Name <br/>
            @Html.EditorFor(model => model.LastName)
        </p>

        <p>
            Age <br/>
            @Html.EditorFor(model => model.Age)
        </p>
        <p>
            Gender <br/>
            @Html.EditorFor(model => model.Gender)
        </p>
        <p>
            Departments <br/>
            @Html.DropDownListFor(model => model.DepartmentId, ViewBag.Departments as SelectList)
        </p>
        <p>
            Experience <br/>
            @Html.DropDownListFor(m => m.ExperienceIds, ViewBag.ProgrammingLanguages as SelectList, new { multiple = "true" })
        </p>
        <p>
            <input type="submit" value="Add employee"/>
        </p>
    </fieldset>
}

Netevia/Views/Employee/Delete.cshtml
@model Netevia.Models.EmployeeViewModel

@{
    ViewBag.Title = "Delete Employee";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Delete" method="post">
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
</form>

Netevia/Views/Employee/Edit.cshtml
@model Netevia.Models.EditEmployeeViewModel

@{
    ViewBag.Title = "Edit Employee";
}

<h2>@ViewBag.Title</h2>

@Html.HiddenFor(model => model.Id)
@using (Html.BeginForm())
{
    <fieldset>
        <legend>Add</legend>

        <p>
            First Name <br/>
            @Html.EditorFor(model => model.FirstName)
        </p>

        <p>
            Last Name <br/>
            @Html.EditorFor(model => model.LastName)
        </p>

        <p>
            Age <br/>
            @Html.EditorFor(model => model.Age)
        </p>
        <p>
            Gender <br/>
            @Html.EditorFor(model => model.Gender)
        </p>
        <p>
            Departments <br/>
            @Html.DropDownListFor(model => model.DepartmentId, ViewBag.Departments as SelectList)
        </p>
        <p>
            Experience <br/>
            @Html.DropDownListFor(m => m.ExperienceIds, ViewBag.ProgrammingLanguages as SelectList, new { multiple = "true" })
        </p>
        <p>
            <input type="submit" value="Редактировать"/>
        </p>
    </fieldset>
}

Netevia/Views/Employee/Index.cshtml
@model IEnumerable<Netevia.Models.EmployeeViewModel>

@{
    ViewBag.Title = "Employee List";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Index">
    <div class="form-group">
        <input type="text" name="searchString" placeholder="Search by name..." class="form-control"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Search" class="btn btn-default"/>
    </div>
    <div class="form-group">
        <a asp-area="" asp-controller="Employee" asp-action="Add">Add Employee</a>
    </div>
</form>

<table class="table">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Department</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Age</td>
            <td>@item.Gender</td>
            <td>@item.Department.Name</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
</table>

Netevia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Netevia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Netevia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Netevia.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Netevia</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                  <ul class="navbar-nav flex-grow-1">
                      <li class="nav-item">
                          <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Add">Register</a>
                      </li>
                  </ul>
              </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Netevia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>